Rails.application.config.assets.precompile += %w( spree/frontend/template/*)
#Rails.application.config.assets.precompile += %w( spree/backend/select2_locale_es-MX.js)
Rails.application.config.assets.precompile += %w( jquery.validate/localization/* )
#Rails.application.config.assets.precompile += %w( jquery.validate/localization/messages_es.js )
#Rails.application.config.assets.precompile += %w( jquery.validate/localization/messages_esmx.js )
#Rails.application.config.assets.precompile += %w( spree/frontend/theme.js )